[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/DCDPUAEM/DCDP/blob/main/02%20An치lisis%20Estad칤stico%20de%20Datos/notebooks/exercises/Practica5_EDA_WS.ipynb)

# 游늷 **Ejercicio: Extracci칩n y An치lisis de Datos de Calidad de Vida Mundial**  

## **Introducci칩n**
En este ejercicio, aplicar치s t칠cnicas de **Web Scraping** para extraer datos de calidad de vida de diferentes pa칤ses y realizar치s un **An치lisis Exploratorio de Datos (EDA)** para identificar tendencias y correlaciones clave.

Trabajar치s con datos extra칤dos desde la p치gina web **[Numbeo](https://www.numbeo.com/quality-of-life/rankings_by_country.jsp)**, una plataforma que proporciona comparaciones de calidad de vida a nivel mundial.  

A lo largo del ejercicio, aplicar치s conceptos fundamentales como:  
九덢잺 **Web Scraping con `requests` y `BeautifulSoup`**  
九덢잺 **Manipulaci칩n y limpieza de datos con `pandas`**  
九덢잺 **An치lisis Exploratorio de Datos (EDA)**  
九덢잺 **Generaci칩n y exportaci칩n de datos estructurados en `CSV`**  

---

## **칈ndices de Calidad de Vida Extra칤dos**
El conjunto de datos incluir치 las siguientes m칠tricas por pa칤s:  

| **칈ndice**                            | **Descripci칩n** |
|----------------------------------------|----------------|
| **Rank**                               | Posici칩n del pa칤s en el ranking general de calidad de vida. |
| **Country**                            | Nombre del pa칤s analizado. |
| **Quality of Life Index**              | 칈ndice general de calidad de vida (ponderaci칩n de varios factores). |
| **Purchasing Power Index**             | Capacidad adquisitiva de los ciudadanos en relaci칩n con el costo de vida. |
| **Safety Index**                        | Nivel de seguridad y criminalidad en el pa칤s. |
| **Health Care Index**                   | Calidad y acceso a los servicios de salud. |
| **Cost of Living Index**                | Comparaci칩n del costo de vida con respecto a otros pa칤ses. |
| **Property Price to Income Ratio**      | Relaci칩n entre el precio de la vivienda y el ingreso promedio. |
| **Traffic Commute Time Index**          | Tiempo promedio de desplazamiento en el tr치fico. |
| **Pollution Index**                     | Niveles de contaminaci칩n ambiental en el pa칤s. |
| **Climate Index**                       | Evaluaci칩n del clima y condiciones meteorol칩gicas en la regi칩n. |
| **Year**                                | A침o en que se recopilaron los datos. |

游늷 **Objetivo:** Obtener datos hist칩ricos de los 칰ltimos 10 a침os y evaluar la evoluci칩n de estos indicadores.

---

## **Actividades**
**Realizar Web Scraping** para extraer los datos de Numbeo.  
**Estructurar los datos en un `DataFrame` de Pandas.**  
**Limpiar y transformar los datos** para que sean analizables.  
**Guardar los datos en un archivo CSV** para an치lisis posterior.  
**Realizar un An치lisis Exploratorio de Datos (EDA)** para visualizar tendencias y correlaciones.
**Comparar comportamientos** de los datos de Mexico vs el Mundo.

In [3]:
# Importamos las librer칤as necesarias
import requests  # Para hacer solicitudes HTTP y obtener datos de la web
from bs4 import BeautifulSoup  # Para analizar HTML y extraer informaci칩n
import pandas as pd  # Para manipulaci칩n de datos en tablas
from datetime import datetime  # Para trabajar con fechas y tiempos

# 游댳 Definimos el encabezado 'User-Agent' para evitar bloqueos por parte de la p치gina web
HEADERS = {
     _______  # (COMPLETAR)
}

# 游댳 Determinamos el rango de a침os a analizar
current_year =  _______  # (COMPLETAR)  # Obtiene el a침o actual
starting_year = _______  # (COMPLETAR) Define el primer a침o a analizar (칰ltimos 10 a침os)

# Creamos una lista vac칤a para almacenar la informaci칩n extra칤da
data = []

# 游댳 Iteramos sobre los 칰ltimos 10 a침os, analizando cada uno
for year in range(starting_year, _______):  # (COMPLETAR) Definir correctamente el rango
    for half in ["", "-mid"]:  # "" para el primer semestre, "-mid" para el segundo semestre
        formatted_year = _______  # (COMPLETAR) Formatear el a침o correctamente para el URL

        # Evita analizar el segundo semestre del a침o actual, ya que puede no tener datos a칰n
        if formatted_year ==  _______  # (COMPLETAR)
            continue
            
        # 游댳 Construimos la URL del sitio web de Numbeo
        url = f"https://www.numbeo.com/quality-of-life/rankings_by_country.jsp?title={formatted_year}"
        
        # (COMPLETAR) Hacer la solicitud HTTP a la URL usando requests.get()
        response = _______

        # (COMPLETAR) Verificar si la respuesta fue exitosa, de lo contrario, detener el programa
        response.raise_for_status()

        # 游댳 Parseamos el contenido HTML usando BeautifulSoup
        soup = _______  # (COMPLETAR) Usar BeautifulSoup para analizar el HTML
        
        # 游댳 Buscamos la tabla que contiene los datos
        table = soup.find _______  # (COMPLETAR)
        if not table:  # Si no hay tabla, pasamos al siguiente a침o
            continue
        
        # 游댳 Definimos los nombres de las columnas que tendr치n nuestros datos
        headers =  _______  # (COMPLETAR)

        rank = 1  # Inicializamos el ranking para cada a침o
        
        # 游댳 Extraemos los datos fila por fila
        for row in table.find_all('tr'):
            columns = row.find_all('td')
        
            # Si la primera columna est치 vac칤a, asignamos manualmente el ranking
            if columns and columns[0].text.strip() == "":
                rank_value = rank  # Asignamos el ranking manualmente
                columns = _______  # (COMPLETAR) Eliminar la primera celda vac칤a
            else:
                rank_value = rank  # Usamos el ranking normal
            
            # 游댳 Verificamos que la cantidad de columnas sea correcta antes de procesarlas
            if len(columns) == len(headers) - 2:  # -2 porque agregamos Rank y Year manualmente
                row_data = [rank_value] + [col.text.strip() for col in columns]  # Extraemos y limpiamos los datos
                
                # 游댳 Ajustamos el formato del a침o
                if half == "-mid":
                    row_data.append(_______)  # (COMPLETAR) Convertir "2015-mid" en "2015/2"
                else:
                    row_data.append(_______)  # (COMPLETAR) Mantener el a침o normal
                
                # Guardamos la fila en la lista de datos
                data.append(row_data)
                rank += 1  # Incrementamos el ranking

# 游댳 Convertimos la lista en un DataFrame de Pandas
df = pd.DataFrame(data, columns=_______)  # (COMPLETAR) Incluir headers como nombres de columnas

# 游댳 Guardamos el DataFrame en un archivo CSV (Opcional)
# df.to_csv("quality_of_life_indices_by_country.csv", index=False)

# 游댳 Mostramos el DataFrame resultante
df

,Rank,Country,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Year
0,1,Switzerland,222.9,146.5,73.2,66.3,126.0,7.3,25.6,24.1,-,2015
1,2,Germany,195.9,111.8,71.5,75.6,76.3,6.6,31.1,28.3,-,2015
2,3,Sweden,193.9,110.9,57.9,76.3,82.9,9.2,26.9,15.1,-,2015
3,4,United States,192.5,126.1,50.0,67.8,76.5,2.6,36.0,31.4,-,2015
4,5,Finland,190.2,101.2,70.5,69.4,89.7,7.0,33.2,14.9,-,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
1578,84,Egypt,85.3,21.4,52.7,47.3,19.0,18.2,48.0,82.7,92.0,2025
1579,85,Sri Lanka,81.1,18.5,57.9,71.4,33.5,34.2,54.5,57.9,59.1,2025
1580,86,Venezuela,79.7,16.0,19.3,38.7,35.9,15.1,32.8,75.1,99.9,2025
1581,87,Bangladesh,73.9,35.9,38.4,42.2,20.9,12.8,57.1,85.4,71.3,2025
1582,88,Nigeria,21.5,11.1,33.4,49.1,26.4,45.7,65.3,87.9,60.8,2025

In [6]:
df.describe(include='all')

,Rank,Country,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Year
count,1583.000000,1583,1583,1583,1583,1583,1583,1583,1583,1583,1583,1583
unique,NaN,98,948,863,510,403,645,281,329,637,418,21
top,NaN,Switzerland,162.3,40.8,53.2,75.5,34.7,11.0,29.1,62.9,-,2025
freq,NaN,21,7,8,11,13,10,21,23,10,143,88
mean,39.054327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,23.113272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,57.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,88.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1583 entries, 0 to 1582
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Rank                            1583 non-null   int64
 1   Country                         1583 non-null   object
 2   Quality of Life Index           1583 non-null   object
 3   Purchasing Power Index          1583 non-null   object
 4   Safety Index                    1583 non-null   object
 5   Health Care Index               1583 non-null   object
 6   Cost of Living Index            1583 non-null   object
 7   Property Price to Income Ratio  1583 non-null   object
 8   Traffic Commute Time Index      1583 non-null   object
 9   Pollution Index                 1583 non-null   object
 10  Climate Index                   1583 non-null   object
 11  Year                            1583 non-null   object
dtypes: int64(1), object(11)
memory usage: 148.5+ KB

In [8]:
 _______  # (COMPLETAR)

,Rank,Country,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Year
45,46,Mexico,85.0,59.5,46.2,67.8,41.3,6.3,36.9,68.8,-,2015
118,33,Mexico,125.6,91.4,47.0,69.1,38.1,5.7,33.4,64.9,-,2015/2
181,39,Mexico,137.0,76.5,49.2,68.1,35.0,6.2,37.1,64.6,58.8,2016
231,33,Mexico,142.8,66.9,49.6,68.0,33.1,6.6,38.9,66.8,82.5,2016/2
304,45,Mexico,129.1,60.1,49.7,70.1,29.8,6.9,41.7,66.7,60.7,2017
364,38,Mexico,120.7,51.4,49.4,69.8,36.3,7.0,39.8,66.5,78.4,2017/2
425,43,Mexico,126.4,58.2,48.9,68.6,33.6,7.8,42.0,66.1,82.5,2018
489,47,Mexico,124.0,53.9,47.9,69.6,30.5,9.7,42.3,66.2,86.0,2018/2
555,47,Mexico,123.5,50.0,47.7,69.7,32.7,10.2,39.1,66.0,86.3,2019
628,49,Mexico,122.4,47.0,47.5,69.4,34.3,10.0,38.2,66.9,87.5,2019/2
706,50,Mexico,118.5,41.8,46.0,70.1,35.7,10.7,39.4,66.1,86.3,2020
786,50,Mexico,120.6,38.2,46.7,72.1,30.9,10.7,39.2,63.3,86.3,2020/2
867,49,Mexico,120.3,35.5,45.0,72.5,35.1,10.5,39.0,61.2,86.6,2021
951,50,Mexico,119.8,31.3,45.8,72.5,36.7,10.9,39.2,59.9,88.5,2021/2
1031,47,Mexico,124.9,38.6,46.3,72.8,35.3,8.7,39.3,58.5,84.0,2022
1118,47,Mexico,126.9,41.1,46.1,72.8,35.1,8.2,39.2,58.3,85.5,2022/2
1205,47,Mexico,127.0,43.5,45.6,72.5,37.3,8.4,39.3,58.5,85.8,2023
1290,48,Mexico,125.0,39.9,45.9,72.6,42.4,8.6,39.2,58.5,85.5,2023/2
1376,50,Mexico,123.9,38.0,46.2,72.5,43.8,10.7,39.2,58.1,90.0,2024
1462,51,Mexico,126.6,45.4,46.3,72.4,40.2,10.7,39.4,58.2,88.5,2024/2
1549,55,Mexico,126.3,48.3,46.6,72.5,34.5,11.8,39.1,58.4,85.3,2025